# Generated by Django 2.2.5 on 2019-09-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='originator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Originator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='originator',
            name='email',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='originator',
            name='pesel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='originator',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
