# Generated by Django 2.2.5 on 2019-09-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190902_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='finish_date',
            new_name='end_date',
        ),
    ]
