# Generated by Django 2.2.5 on 2019-09-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190902_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originator',
            name='pesel',
            field=models.BigIntegerField(verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_long',
            field=models.TextField(max_length=2000, verbose_name='Opis projektu (max. 2000 znków ze spacjami)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_short',
            field=models.TextField(max_length=1000, verbose_name='Skrócony opis projektu (max. 1000 znków ze spacjami)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Tytuł wniosku'),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.IntegerField(choices=[(1, 'jeleniogórski'), (2, 'legnicki'), (3, 'wałbrzyski'), (4, 'wrocławski'), (5, 'm. Wrocław')], verbose_name='Subregion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Data ropoczęcia'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subject',
            field=models.IntegerField(choices=[(1, 'sport'), (2, 'turystyka'), (3, 'kultura'), (4, 'wsparcie osób z niepełnosprawnościami'), (5, 'wsparcie społeczeństwa obywatelskiego'), (6, 'wsparcie seniorów'), (7, 'wsparcie rzemiosła')], verbose_name='Obszar merytoryczny'),
        ),
    ]
