# Generated by Django 2.2.5 on 2019-09-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190902_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coast_name', models.CharField(max_length=64, verbose_name='Nazwa kosztu')),
                ('grant_coast', models.FloatField(verbose_name='Koszt z dotacji (w zł)')),
                ('other_coast', models.FloatField(verbose_name='Finansowanie z innych źródeł (w zł)')),
                ('whole_coast', models.FloatField()),
            ],
        ),
    ]
