# Generated by Django 2.2.5 on 2019-09-06 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_coast'),
    ]

    operations = [
        migrations.AddField(
            model_name='coast',
            name='originator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Originator'),
            preserve_default=False,
        ),
    ]
