# Generated by Django 2.2.5 on 2019-09-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_coast_originator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coast',
            name='grant_coast',
            field=models.FloatField(null=True, verbose_name='Koszt z dotacji (w zł)'),
        ),
        migrations.AlterField(
            model_name='coast',
            name='other_coast',
            field=models.FloatField(null=True, verbose_name='Finansowanie z innych źródeł (w zł)'),
        ),
    ]
