# Generated by Django 2.2.5 on 2019-09-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190906_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coast',
            name='grant_coast',
            field=models.FloatField(default=0, verbose_name='Koszt z dotacji (w zł)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coast',
            name='other_coast',
            field=models.FloatField(default=0, verbose_name='Finansowanie z innych źródeł (w zł)'),
            preserve_default=False,
        ),
    ]
