# Generated by Django 2.2.5 on 2019-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190906_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
