# Generated by Django 2.2.5 on 2019-09-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190913_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coast',
            name='originator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coas_originator', to='projects.Originator'),
        ),
    ]
