# Generated by Django 2.2.5 on 2019-09-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190913_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=64, verbose_name='Nazwa kosztu')),
                ('grant_cost', models.FloatField(verbose_name='Koszt z dotacji (w zł)')),
                ('other_cost', models.FloatField(verbose_name='Finansowanie z innych źródeł (w zł)')),
                ('whole_cost', models.FloatField()),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_originator', to='projects.Originator')),
            ],
        ),
        migrations.DeleteModel(
            name='Coast',
        ),
    ]
