# Generated by Django 2.2.5 on 2019-09-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190913_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comment',
            field=models.TextField(default=0, verbose_name='Uwagi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='verified',
            field=models.IntegerField(choices=[(0, 'pozytywna'), (1, 'negatywna')], default='0', verbose_name='Weryfikacja formalna'),
            preserve_default=False,
        ),
    ]
