# Generated by Django 2.2.5 on 2019-09-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20190914_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='verified',
            field=models.IntegerField(choices=[(0, 'negatywna'), (1, 'pozytywna')], default=0, verbose_name='Weryfikacja formalna'),
        ),
    ]
