# Generated by Django 2.2.5 on 2019-09-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20190914_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originator',
            name='pesel',
            field=models.CharField(max_length=11, verbose_name='PESEL'),
        ),
    ]
