# Generated by Django 2.2.5 on 2019-09-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20190914_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='verified',
            field=models.IntegerField(blank=True, choices=[('', ''), (0, 'negatywna'), (1, 'pozytywna')], null=True, verbose_name='Weryfikacja formalna'),
        ),
    ]
