# Generated by Django 2.2.5 on 2019-09-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20190914_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
