# Generated by Django 2.2.5 on 2019-09-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
