# Generated by Django 2.2.5 on 2019-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20190915_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nazwisko')),
                ('pesel', models.CharField(max_length=11, verbose_name='PESEL')),
                ('phone', models.IntegerField(verbose_name='Numer telefonu')),
                ('email', models.EmailField(max_length=64, verbose_name='E-mail')),
                ('post_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
            ],
        ),
    ]
