# Generated by Django 2.2.5 on 2019-09-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_voters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voters',
            new_name='Voter',
        ),
    ]
